#!/bin/bash
set -e

if [ $# -lt 1 ]; then
    echo "Usage: test_mongo_release <release> [<install_dir>] [<data_dir>]"
    echo "e.g. test_mongo_release mongodb-linux-x86_64-ubuntu1204-3.4.2 travis/mongodb travis/data"
    exit
fi

port=$1
ssl_port=$2

# TODO: add method to read env or have default for tests
parallel --gnu MONGODB_RUST_DRIVER_TEST_PORT="mongodb://localhost:$port" cargo test --verbose ::: $ports

MONGODB_RUST_DRIVER_TEST_PORT="mongodb://localhost:$port" MONGODB_RUST_DRIVER_TEST_SSL_PORT="mongodb://localhost:$ssl_port" cargo test --features ssl --verbose

